### ISSUE TITLE
Link to sample input is broken

### ISSUE THREAD

**Issue by sXperfect** [BDM-Lab/Hierarchical3DGenome#5]
Hi,

Could you update the link to the sample input dataset (http://sysbio.rnet.missouri.edu/bdm_download/Hierarchical3DGenome/Hierarchical3DGenome/)? It seems that the link is dead at the moment.

**Comment by jianlin-cheng** [comment]
The sample input dataset can be downloaded here: http://calla.rnet.missouri.edu/Hierarchical3DGenome/

**Comment by jianlin-cheng** [comment]
The problem has been fixed.
